apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikemanageapp
  namespace: gbike
  labels:
    app: bikemanageapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bikemanageapp
  template:
    metadata:
      labels:
        app: bikemanageapp
    spec:
      containers:
        - name: bikemanageapp
          image: ysykingg.azurecr.io/bikemanageapp:v1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
