apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikemanager
  namespace: gbike
  labels:
    app: bikemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bikemanager
  template:
    metadata:
      labels:
        app: bikemanager
    spec:
      containers:
        - name: bikemanager
          image: ysykingg.azurecr.io/bikeManager:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
