apiVersion: apps/v1
kind: Deployment
metadata:
  name: userDeposit
  labels:
    app: userDeposit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userDeposit
  template:
    metadata:
      labels:
        app: userDeposit
    spec:
      containers:
        - name: userDeposit
          image: ysykingg.azurecr.io/userdeposit:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
           initialDelaySeconds: 120
           timeoutSeconds: 2
           periodSeconds: 5
            failureThreshold: 5
#          livenessProbe:
#            httpGet:
#              path: '/actuator/health'
#              port: 8081
#            initialDelaySeconds: 3
#            periodSeconds: 5
